packages:
  branch_codenames:
    master: precise-unstable
    production: precise-stable

jobs:
  imagemagick:
    builder: make
    base: "quay.io/madebymany/build-bases:precise"
    promote_through:
      - precise-unstable
      - precise-stable
    packages:
      - type: debian
        name: imagemagick
        version: "8:6.9.0-0"
        depends: 
          - libc6
          - libbz2-1.0
          - libfontconfig1
          - libfreetype6
          - libgomp1
          - libjasper1
          - libjpeg8
          - liblcms1
          - liblqr-1-0
          - libltdl7
          - libpng12-0
          - libtiff4
          - libx11-6
          - libxext6
          - libxml2
          - zlib1g
          - libpango1.0-0
          - libopenexr6
          - libdjvulibre21
        target: install
        repos:
          - mxm-public
